### ISSUE TITLE
不使用wait-for-it.sh 也能跑吗

### ISSUE THREAD

**Issue by hujesse83** [andochiwa/Online-Education-Backend#1]
不使用wait-for-it.sh 也能跑吗

**Comment by andochiwa** [comment]
如果你不使用docker-compose进行部署的话可以

否则不行，因为docker-compose无法控制依赖启动顺序

**Comment by hujesse83** [comment]
能介绍下wait-fot-it 是干啥的吗，我不大看不懂

**Comment by andochiwa** [comment]
https://github.com/vishnubob/wait-for-it
